"""add unique

Revision ID: 135c62ca71ec
Revises: ddce3f9bd43c
Create Date: 2023-12-11 14:43:20.209003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135c62ca71ec'
down_revision: Union[str, None] = 'ddce3f9bd43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_users', type_='unique')
    # ### end Alembic commands ###
