"""empty message

Revision ID: 48eeff9d6ea9
Revises: e0b35d573c80
Create Date: 2023-12-15 01:19:17.260725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48eeff9d6ea9'
down_revision: Union[str, None] = 'e0b35d573c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_detail_admin', 'gender',
               existing_type=mysql.ENUM('laki', 'perempuan'),
               type_=sa.Enum('laki-laki', 'perempuan'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_detail_admin', 'gender',
               existing_type=sa.Enum('laki-laki', 'perempuan'),
               type_=mysql.ENUM('laki', 'perempuan'),
               existing_nullable=False)
    # ### end Alembic commands ###
