"""remove uuid userlogin

Revision ID: 56647dc68c40
Revises: 9eb60db44cb7
Create Date: 2023-12-14 10:51:09.753163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56647dc68c40'
down_revision: Union[str, None] = '9eb60db44cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user_login', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user_login', sa.Column('uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###
