"""empty message

Revision ID: 78ed4004afb9
Revises: 
Create Date: 2023-12-21 18:07:55.449359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ed4004afb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_datum_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kelas')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('admin', 'guru', 'siwsa', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_detail_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Enum('laki-laki', 'perempuan'), nullable=False),
    sa.Column('agama', sa.Enum('islam', 'kristen', 'katolik', 'hindu', 'budha', 'konghucu', name='agamaenum'), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('telp', sa.String(length=14), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_detail_guru',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Enum('laki', 'perempuan', name='genderenum'), nullable=False),
    sa.Column('agama', sa.Enum('islam', 'kristen', 'katolik', 'hindu', 'budha', 'konghucu', name='agamaenum'), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('telp', sa.String(length=14), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_detail_siswa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Enum('laki', 'perempuan', name='genderenum'), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=64), nullable=True),
    sa.Column('tgl_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.Enum('islam', 'kristen', 'katolik', 'hindu', 'budha', 'konghucu', name='agamaenum'), nullable=True),
    sa.Column('nama_ortu', sa.String(length=64), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('telp', sa.String(length=14), nullable=True),
    sa.Column('qr_name', sa.String(length=255), nullable=True),
    sa.Column('photo_name', sa.String(length=255), nullable=True),
    sa.Column('idcard_name', sa.String(length=255), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['tb_datum_kelas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refreh_token', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expire_token', sa.DateTime(), nullable=False),
    sa.Column('counter_login', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user_login')
    op.drop_table('tb_detail_siswa')
    op.drop_table('tb_detail_guru')
    op.drop_table('tb_detail_admin')
    op.drop_table('tb_users')
    op.drop_table('tb_datum_kelas')
    # ### end Alembic commands ###
