"""add table detail all user

Revision ID: 8988927d856f
Revises: 7402db916063
Create Date: 2023-12-14 13:55:12.500272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8988927d856f'
down_revision: Union[str, None] = '7402db916063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_detail_siswa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Enum('laki', 'perempuan', name='genderenum'), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=64), nullable=True),
    sa.Column('tgl_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.Enum('islam', 'kristen', 'hindu', 'budha', 'konghucu', name='agamaenum'), nullable=True),
    sa.Column('nama_ortu', sa.String(length=64), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('telp', sa.String(length=14), nullable=True),
    sa.Column('qr_name', sa.String(length=255), nullable=True),
    sa.Column('photo_name', sa.String(length=255), nullable=True),
    sa.Column('idcard_name', sa.String(length=255), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('tb_users', 'role',
               existing_type=mysql.ENUM('admin', 'guru', 'siswa'),
               type_=sa.Enum('admin', 'guru', 'siwsa', name='roleenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'role',
               existing_type=sa.Enum('admin', 'guru', 'siwsa', name='roleenum'),
               type_=mysql.ENUM('admin', 'guru', 'siswa'),
               existing_nullable=False)
    op.drop_table('tb_detail_siswa')
    # ### end Alembic commands ###
