"""add field expire token

Revision ID: 9eb60db44cb7
Revises: bf17d18051a9
Create Date: 2023-12-14 10:44:27.156228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb60db44cb7'
down_revision: Union[str, None] = 'bf17d18051a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user_login', sa.Column('expire_token', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user_login', 'expire_token')
    # ### end Alembic commands ###
