"""empty message

Revision ID: eeee29dab8ae
Revises: 1f1898bcb30c
Create Date: 2023-12-15 01:13:10.698984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eeee29dab8ae'
down_revision: Union[str, None] = '1f1898bcb30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_detail_admin', 'gender',
               existing_type=mysql.ENUM('laki-laki', 'perempuan'),
               type_=sa.Enum('laki', 'perempuan', name='genderenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_detail_admin', 'gender',
               existing_type=sa.Enum('laki', 'perempuan', name='genderenum'),
               type_=mysql.ENUM('laki-laki', 'perempuan'),
               existing_nullable=False)
    # ### end Alembic commands ###
