"""relasi siswa -> kelas

Revision ID: f30e717e1b23
Revises: fdb14450b35d
Create Date: 2023-12-18 23:26:41.242786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30e717e1b23'
down_revision: Union[str, None] = 'fdb14450b35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tb_detail_siswa', 'tb_datum_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_detail_siswa', type_='foreignkey')
    # ### end Alembic commands ###
