"""empty message

Revision ID: fae095e57f55
Revises: 91ac9cca36dc
Create Date: 2023-12-15 01:16:27.617378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fae095e57f55'
down_revision: Union[str, None] = '91ac9cca36dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_detail_admin', 'gender',
               existing_type=mysql.ENUM('laki-laki', 'perempuan'),
               type_=sa.Enum('laki', 'perempuan', name='genderenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_detail_admin', 'gender',
               existing_type=sa.Enum('laki', 'perempuan', name='genderenum'),
               type_=mysql.ENUM('laki-laki', 'perempuan'),
               existing_nullable=False)
    # ### end Alembic commands ###
