"""add attribute unique

Revision ID: fdb14450b35d
Revises: 7987d08596c6
Create Date: 2023-12-18 23:20:25.021721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb14450b35d'
down_revision: Union[str, None] = '7987d08596c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_datum_kelas', ['kelas'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_datum_kelas', type_='unique')
    # ### end Alembic commands ###
